name: MLFrame
on: push
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate metrics report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USDA_API_KEY: ${{ secrets.USDA_API_KEY }}
        run: |
          # ML workflow runners
          # Install requirements
          #pip install -r requirements.txt
          # DVC workflow from dvc.yaml file
          #dvc repro